---

- name: start apache
  service:
    name: "{{ apache_server_service_name | default(apache2) }}"
    state: started
  when: apache_server_state is defined and apache_server_state == "running"

- name: stop apache
  service:
    name: "{{ apache_server_service_name | default(apache2) }}"
    state: stopped
  when: apache_server_state is defined and apache_server_state == "stopped"